import Head from 'next/head';
import React from 'react';
import { Lists } from '.';
import { IListPattern } from '../interfaces';
import { Header } from './Header';
import { TopNavigation } from './TopNavigation';

interface IAppMain {
  data: IListPattern[];
  name: String;
}

export const AppMain: React.FC<IAppMain> = ({ data, name }) => {
  return (
    <div className="container">
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <TopNavigation />
      <Lists data={data} />
    </div>
  );
};
