import Head from 'next/head';
import React from 'react';
import { Header, TopNavigation } from '../components';

interface ILayout {
  children: React.ReactNode;
  name: String;
}

export const Layout: React.FC<ILayout> = ({ children, name }) => {
  return (
    <div className="container">
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <TopNavigation />
      {children}
    </div>
  );
};
