import Head from 'next/head';
import { NextApiRequest, NextApiResponse } from 'next';

import { Header, Lists, TopNavigation } from '../components';

export default function Home({ data }: any) {
  return (
    <div className="container">
      <Head>
        <title>Next RGXP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header />
      <TopNavigation />
      <Lists data={data} />
    </div>
  );
}

export async function getServerSideProps(req: NextApiRequest, res: NextApiResponse<any>) {
  const dataJSON = await fetch('https://60feed9f257411001707883e.mockapi.io/all');
  const data = await dataJSON.json();

  return {
    props: {
      data,
    }, // will be passed to the page component as props
  };
}
