import Head from 'next/head';
import { NextApiRequest, NextApiResponse } from 'next';

import { Header, Lists, TopNavigation } from '../components';
import { IListPattern } from '../interfaces';

interface IHome {
  data: IListPattern[];
}

const Home: React.FC<IHome> = ({ data }) => {
  return (
    <div className="container">
      <Head>
        <title>Next RGXP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header />
      <TopNavigation />
      <Lists data={data} />
    </div>
  );
};

export default Home;

export async function getServerSideProps(
  req: NextApiRequest,
  res: NextApiResponse<IListPattern[]>,
) {
  const dataJSON = await fetch('https://60feed9f257411001707883e.mockapi.io/all');
  const data: IListPattern[] = await dataJSON.json();

  return {
    props: {
      data,
    }, // will be passed to the page component as props
  };
}
