import Head from 'next/head';
import { Header, Lists, TopNavigation } from '../components';

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Next RGXP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <TopNavigation />
      <Lists />
    </div>
  );
}
